@baseUrl=http://localhost:3333

@answerId=e315afc6-4f44-41bc-bb05-b36d1f9cdf16
@questionId=9866781b-7149-47f9-bc27-dcef872d33bc
@commentId=cfb0fbae-34b7-4f54-95f2-b68a969218c6
@authToken={{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "email@example.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "email@example.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 1234",
  "content": "Conteudo da pergunta"
}


###

# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/nova-pergunta-2
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
POST {{baseUrl}}/questions/9866781b-7149-47f9-bc27-dcef872d33bc
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pergunta Editada",
  "content": "Conteudo da pergunta Editada"
}

###

# @name delete_question
DELETE {{baseUrl}}/questions/9866781b-7149-47f9-bc27-dcef872d33bc
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name answer_question
POST {{baseUrl}}/questions/9866781b-7149-47f9-bc27-dcef872d33bc/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Resposta 4",
  "attachmentsIds": []
}

###

# @name edit_answer
POST {{baseUrl}}/answers/{{answerId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Resposta Editada",
  "attachmentsIds": []
}

###

# @name delete_answer
DELETE  {{baseUrl}}/answers/{{answerId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_question_answers
GET  {{baseUrl}}/question/{{questionId}}/answers?p=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name choose_best_answer
PATCH {{baseUrl}}/answers/{{answerId}}/choose-best
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name comment_on_question
POST {{baseUrl}}/questions/{{questionId}}/comments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "conteudo do comentario"
}


###

# @name delete_question_comment
POST {{baseUrl}}/questions/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "conteudo do comentario"
}

###

# @name comment_on_answer
POST {{baseUrl}}/answers/{{answerId}}/comments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "conteudo do comentario"
}
