@baseUrl=http://localhost:3333
@authToken={{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "email@example.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "email@example.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 1234",
  "content": "Conteudo da pergunta"
}


###

# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/nova-pergunta-2
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
POST {{baseUrl}}/questions/9866781b-7149-47f9-bc27-dcef872d33bc
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pergunta Editada",
  "content": "Conteudo da pergunta Editada"
}
