@baseUrl=http://localhost:3333

@answerId=191a9bc0-a45a-4519-bdce-f47052560783
@questionId=77d51ea6-3d3f-4ba0-989a-41a421541c5c
@authToken={{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "email@example.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "email@example.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 1234",
  "content": "Conteudo da pergunta"
}


###

# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/nova-pergunta-2
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
POST {{baseUrl}}/questions/9866781b-7149-47f9-bc27-dcef872d33bc
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pergunta Editada",
  "content": "Conteudo da pergunta Editada"
}

###

# @name delete_question
DELETE {{baseUrl}}/questions/9866781b-7149-47f9-bc27-dcef872d33bc
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name answer_question
POST {{baseUrl}}/questions/9866781b-7149-47f9-bc27-dcef872d33bc/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Resposta da pergunta",
  "attachmentsIds": []
}

###

# @name edit_answer
POST {{baseUrl}}/answers/{{answerId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Resposta Editada",
  "attachmentsIds": []
}

###

# @name delete_answer
DELETE  {{baseUrl}}/answers/{{answerId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}
